build:
    environment:
        python: 3.5.0
    dependencies:
        before:
            - pip install -r requirements-dev.txt
    tests:
        override:
            - paver test
            -
                command: paver coverage
                coverage:
                    file: '.coverage'
